services:
  php:
    build:
      context: .
    image: cassioik/laravel-11-frankenphp:local
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - .:/app